version: "3"

networks:
  hive-default:
    name: hive-default
    driver: bridge
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.1.2-java8
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - 9870:9870
      - 9000:9000
    networks:
      - hive-default
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.2-java8
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    networks:
      - hive-default
    ports:
      - "9866:9866"
  hive-server:
    image: hive:v3.1.2
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
    networks:
      - hive-default
  hive-metastore:
    image: hive:v3.1.2
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:9870 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
    networks:
      - hive-default
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:3.1.0
    ports:
      - "5432:5432"
    networks:
      - hive-default
  presto-coordinator:
    image: shawnzhu/prestodb:0.181
    ports:
      - "8080:8080"
    networks:
      - hive-default

volumes:
  namenode:
  datanode:clear
